service: serverless-typescript-template

plugins:
  - - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: ${opt:stage}
  logRetentionInDays: 180
  versionFunctions: false
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}

custom:
  prefix: ${self:service}-${self:provider.stage}

functions:
  - ${file(./resources/routes/user.yml)}

resources:
  - ${file(./resources/routes-roles.yml)}
