service: serverless-typescript-template

plugins:
  - serverless-offline

stages:
  default:
    resolvers:
      shared-account:
        type: aws
        region: ${env:AWS_REGION}
        accessKeyId: ${env:AWS_ACCESS_KEY_ID}
        secretAccessKey: ${env:AWS_SECRET_ACCESS_KEY}

provider:
  name: aws
  region: ${env:AWS_REGION}
  runtime: nodejs20.x
  stage: ${opt:stage}
  logRetentionInDays: 180
  versionFunctions: false
  timeout: 30
  resolver: shared-account

custom:
  prefix: ${self:service}-${self:provider.stage}
  STAGE: ${self:provider.stage}
  AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ${env:AWS_REGION}
  DATABASE_PREFIX: ${env:DATABASE_PREFIX}

functions:
  - ${file(./resources/routes/user.yml)}

resources:
  - ${file(./resources/routes-roles.yml)}
